<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AllStudentInfo.aspx.cs" Inherits="SchoolManagementSystem.AllStudentInfo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
            font-size: xx-large;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 344px;
            font-size: x-large;
        }
        .auto-style4 {
            font-size: x-large;
        }
        .auto-style5 {
            text-align: right;
        }
        .auto-style6 {
            width: 352px;
            text-align: left;
        }
        .auto-style7 {
            height: 40px;
        }
        .auto-style8 {
            height: 40px;
            width: 167px;
        }
        .auto-style9 {
            height: 40px;
            width: 510px;
            text-align: left;
        }
        .auto-style10 {
            font-size: large;
        }
        .auto-style11 {
            color: #663300;
        }
    </style>
</head>
<body bgcolor ="#cccccc">
    <form id="form1" runat="server">
    <div class="auto-style1">
     <div class="auto-style14">
            <span class="auto-style11">School Management System<br />
            <br />
            </span><br />
        </div>
        <table class="auto-style2">
            <tr>
                <td class="auto-style6">
                    <asp:LinkButton ID="LinkButton2" runat="server" CssClass="auto-style4" OnClick="LinkButton2_Click">Back</asp:LinkButton>
                </td>
                <td class="auto-style3">All Student Information</td>
                <td class="auto-style5">
                    <asp:LinkButton ID="LinkButton1" runat="server" CssClass="auto-style4" OnClick="LinkButton1_Click">Log Out</asp:LinkButton>
                </td>
            </tr>
        </table>
        <br />
        <table class="auto-style2">
            <tr>
                <td class="auto-style8">
        <asp:Button ID="ButtonConfirm" runat="server" OnClick="ButtonConfirm_Click" Text="Confirm" />
    
        <asp:Button ID="ButtonUndo" runat="server" OnClick="ButtonUndo_Click" Text="Undo" />
                </td>
                <td class="auto-style9">
                    <asp:Label ID="LabelMessage" runat="server" CssClass="auto-style10"></asp:Label>
                </td>
                <td class="auto-style7"></td>
            </tr>
        </table>
    
    </div>
        <asp:GridView ID="GridView1" runat="server" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" DataKeyNames="Id" Width="100%">
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>
    </form>
</body>
</html>
